---
- name: Update distro
  hosts: all
  become: yes
  tasks:
    - name: Setup timezone
      timezone:
        name: Asia/Ho_Chi_Minh

    - name: Sync time
      command: timedatectl set-ntp on

    - name: Update distro
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install fail2ban
      apt: package=fail2ban state=present

    - name: Install ufw
      apt: package=ufw state=present

    - name: Configure ufw defaults
      ufw: direction={{ item.direction }} policy={{ item.policy }}
      with_items:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Configure ufw rules
      ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
      with_items:
        - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }

    - name: Enable ufw logging
      ufw: logging=on

    - name: Enable ufw
      ufw: state=enabled

    - name: Install htop
      apt: package=htop state=present

    - name: Deny root from logging in
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(#)?PermitRootLogin \w*$'
        line: 'PermitRootLogin no'
        state: present
