---
- name: Install docker
  hosts: all
  become: yes

  vars:
    compose_version: 2.4.1
    ctop_version: 0.7.7

  tasks:
    - name: Install dependency packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: ansible_distribution == 'Debian'

    - name: Add Ubuntu apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      when: ansible_distribution == 'Ubuntu'

    - name: Add Debian apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable"
      when: ansible_distribution == 'Debian'

    - name: Install docker
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

    - name: Make sure docker is active
      service: name=docker state=started enabled=yes

    - name: Add remote user to "docker" group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-{{ansible_system|lower}}-{{ansible_userspace_architecture}}
        dest: /usr/local/bin/docker-compose
        mode: 0755
        force: yes

    - name: Install ctop
      get_url:
        url: https://github.com/bcicen/ctop/releases/download/v{{ctop_version}}/ctop-{{ctop_version}}-{{ansible_system|lower}}-amd64
        dest: /usr/local/bin/ctop
        mode: 0755
        force: yes
