---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: Install dependency packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: ansible_distribution == 'Debian'

    - name: Add Ubuntu apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      when: ansible_distribution == 'Ubuntu'

    - name: Add Debian apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable"
      when: ansible_distribution == 'Debian'

    - name: Install docker
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

    - name: Make sure docker is active
      service: name=docker state=started enabled=yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
        force: yes

    - name: Install ctop
      get_url:
        url: https://github.com/bcicen/ctop/releases/download/0.7.6/ctop-0.7.6-linux-amd64
        dest: /usr/local/bin/ctop
        mode: 0755
        force: yes
