---
- name: Install oh-my-zsh
  hosts: all
  tasks:
  - name: Installing Zsh and git
    apt: package=zsh,git state=latest update_cache=yes
    become: true

  - name: set default shell
    user:
      name: '{{ ansible_user }}'
      shell: /bin/zsh

  - name: Check if .zshrc exists
    stat:
      path: ~/.zshrc
    register: stat_rc_result

  - name: Check if .oh-my-zsh exists
    stat:
      path: ~/.oh-my-zsh
    register: stat_oh_my_zsh_result

  - name: Cloning oh-my-zsh
    git:
      repo=https://github.com/ohmyzsh/ohmyzsh
      dest=~/.oh-my-zsh
    when: not stat_oh_my_zsh_result.stat.exists

  - name: Creating new ~/.zshrc
    copy:
      src=~/.oh-my-zsh/templates/zshrc.zsh-template
      dest=~/.zshrc

  - name: Change theme
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: '^ZSH_THEME='
      line: ZSH_THEME="agnoster"
