---
- name: Update distro
  hosts: all
  become: yes
  tasks:
    - name: Update distro
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        autoremove: yes
